import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1282,height:800}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173/#/home');
await page.waitForTimeout(1600);
assert.equal(await page.locator('.rail-mark').innerText(),'');
assert(await page.locator('.rail-mark img').evaluate(i=>i.complete && i.naturalWidth>0));
await page.screenshot({path:'qa/emblem-desktop.png'});
const title=page.locator('#intro .section-heading');
const top=await title.evaluate(n=>n.getBoundingClientRect().top+scrollY);
async function scroll(y){await page.evaluate(y=>window.scrollTo({top:y,behavior:'instant'}),y);await page.waitForTimeout(1300);}
await scroll(top-200);
assert(await title.evaluate(n=>n.classList.contains('is-visible')));
assert.equal(await title.locator('h2').evaluate(n=>getComputedStyle(n).opacity),'1');
await scroll(top+700);
assert.equal(await title.evaluate(n=>n.classList.contains('is-visible')),false);
assert.equal(await title.evaluate(n=>n.style.getPropertyValue('--enter-y')),'-32px');
await scroll(top-200);
assert(await title.evaluate(n=>n.classList.contains('is-visible')));
assert.equal(await title.locator('h2').evaluate(n=>getComputedStyle(n).opacity),'1');
await page.screenshot({path:'qa/scroll-return-desktop.png'});
await scroll(0);
assert.equal(await title.evaluate(n=>n.classList.contains('is-visible')),false);
assert.equal(await title.evaluate(n=>n.style.getPropertyValue('--enter-y')),'32px');
await scroll(top-200);
assert(await title.evaluate(n=>n.classList.contains('is-visible')));
await page.emulateMedia({reducedMotion:'reduce'});
await scroll(0);
assert.equal(await title.locator('h2').evaluate(n=>getComputedStyle(n).opacity),'1');
await page.setViewportSize({width:390,height:844});
await page.emulateMedia({reducedMotion:'no-preference'});
await scroll(0);
assert(await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth));
await page.screenshot({path:'qa/motion-mobile.png'});
assert.deepEqual(errors,[]);
console.log('PASS: emblem asset, repeated downward and upward entrances, text visibility, reduced motion, mobile overflow, browser errors.');
await browser.close();
